export { default as SectionBlack } from "./SectionBlack/SectionBlack"
export { default as Headline } from "./Headline/Headline"
export { default as Model3DCurcle } from "./Model3DCurcle/Model3DCurcle"
export { default as Menu } from "./Menu/Menu"
export { default as Logo } from "./Logo/Logo"
export { default as Button } from "./Button/Button"
export { default as BrashDrawing } from "./BrashDrawing/BrashDrawing"
export { default as SocialNetworks } from "./SocialNetworks/SocialNetworks"
export { default as ChartGantt } from "./ChartGantt/ChartGantt"
export { default as TitleSection } from "./TitleSection/TitleSection"
export { default as Modal } from "./Modal/Modal"
export { default as ModalNew } from "./ModalNew/ModalNew"

export { default as InputPhone } from "./InputPhone/InputPhone"

export { default as Icons } from "./Icons"
