import { Task } from "gantt-task-react"

const DataMock: Task[] = [
  {
    start: new Date(2025, 0, 1),
    end: new Date(2025, 1, 15),
    name: "Знакомство, анкетирование",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 1, 15),
    end: new Date(2025, 1, 31),
    name: "Обмеры квартиры",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },

  {
    start: new Date(2025, 1, 31),
    end: new Date(2025, 2, 15),
    name: "Разработка планировочного решения",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },

  {
    start: new Date(2025, 2, 15),
    end: new Date(2025, 3, 15),
    name: "Разработка эскизного проекта интерьера",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 3, 15),
    end: new Date(2025, 4, 15),
    name: "Разработка рабочего проекта интерьера",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 3, 15),
    end: new Date(2025, 3, 30),
    name: "Разработка эскизного проекта мебели",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 30),
    end: new Date(2025, 6, 15),
    name: "Проектирование вентиляции",
    id: "Task 0",
    type: "task",
    progress: 50,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 0),
    end: new Date(2025, 4, 15),
    name: "Проектирование отопления",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 0),
    end: new Date(2025, 4, 15),
    name: "Проектирование водоснабжения",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 0),
    end: new Date(2025, 4, 15),
    name: "Проектирование канализации",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 0),
    end: new Date(2025, 4, 15),
    name: "Проектирование электроснабжения",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 0),
    end: new Date(2025, 4, 15),
    name: "Проектирование электроснабжения",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 0),
    end: new Date(2025, 4, 15),
    name: "Составление сметы",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 4, 15),
    end: new Date(2025, 6, 15),
    name: "Согласование перепланировки",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
  {
    start: new Date(2025, 5, 1),
    end: new Date(2025, 11, 15),
    name: "Авторский надзор",
    id: "Task 0",
    type: "task",
    progress: 100,
    isDisabled: true,
  },
]

export default DataMock
